type MqttParams {
  "MQTT server URL"
  url: String
  "MQTT server port"
  port: Int
  "MQTT Client ID"
  clientId: String
  "MQTT connection user"
  user: String,
  "MQTT connection password"
  password: String,  
}

"Business Contact info"
type Query{
   MqttParams: MqttParams @requireAuth
}