"Async CMD server acknowledge"
type CommandAck{
   "message accepted by the server"
   accepted: Boolean
}

"Vehicle or Driver Block info"
type Block{
   "block unique key, aka ENUM"
   key: String
   "Additional note"
   notes: String
   "Block start time"
   startTime: BigInt
   "Block end time"
   endTime: BigInt
}


"Vehicle info"
type Vehicle {
   "License plate"
   plate: String
   "Current blocks"
   blocks: [Block]   
   "Active flag"
   active: Boolean
}

"Driver info."
type Driver {
   "Driver fullname"
   fullname: String
   "username"
   username: String
   "Current blocks"
   blocks: [Block]
   "Wallet driver"
   wallet: DriverWallet
   "Active flag"
   active: Boolean
   driverCode: String
}

type DriverWallet {
   _id: String
   pockets: DriverWalletPocket
   businessId: String
}

type DriverWalletPocket {
   main: Float
   bonus: Float
}

"Driver's shift info"
type Shift {
   "Shift ID"
   _id: String
   "shift's state"
   state: String,
   "true if business unit allow PayPerService mode"
   allowPayPerService: Boolean,
   "cost for pay per service if it is enabled"
   payPerServicePrice: Int
   "subscription Type REGULAR or PAY_PER_SERVICE"
   subscriptionType: String
   "shift's vehicle"
   vehicle: Vehicle
   "shift's Driver"
   driver: Driver
}

"Client info"
type Client {
   "Full name"
   fullname: String
   "Tip given to the client. Eg. satellites"
   tip: BigInt,
   "Tiping type"
   tipType: String
}

"Geo point"
type Point {
   "Latitude"
   lat: Float
   "Longitude"
   lng: Float
}

"Geo point"
input PointInput {
   "Latitude"
   lat: Float
   "Longitude"
   lng: Float
} 
 
"Location info."
type Location {
   "Accurate location, Exact marker point: Lat,Lng"
   marker: Point
   "Non-Accurate location, describes an area"
   polygon: [Point]
   "City name"
   city: String
   "Zone name"
   zone: String
   "Precise location"
   unaccurateLocation: Boolean
   "Neighborhood name"
   neighborhood: String
   "Street address 1"
   addressLine1: String
   "Street address 2"
   addressLine2: String
   "location notes"
   notes: String
}

"Service info"
type Service {
   "Service Identifier"
   _id: String
   "Service created timestamp."
   timestamp: BigInt
   "Client info"
   client: Client
   "Service vehicle"
   vehicle: Vehicle
   "Passenger pick up location"
   pickUp: Location
   "Passenger drop off location"
   dropOff: Location
   "dropOff especial type eg: AIRPORT, BUS_TERMINAL, OUT_OF_CITY"
   dropOffSpecialType: String
   "Service verification code"
   verificationCode: String
   "Requested features keys"
   requestedFeatures: [String]
   "Payment type key"
   paymentType: String
   "Applicable fare discount"
   fareDiscount: Float
   "pre calculated fare"
   fare: BigInt
   "Tip given to the driver"
   tip: BigInt
   "Exact route taken by the driver"
   route: [Point]   
   "current service state"
   state: String
   "Trip cost"
   tripCost: Int
   destinationCost: Int
}

input ChatMessageInput {
   predefinedMessageId: Int
   textMessage: String
}

type Query {
   "Get driver's assigned vehicles"
   DriverAssignedVehicles: [Vehicle] @requireAuth

   "Get driver's currently open shift"
   OpenShift(
      "Device Identifier"
      deviceIdentifier: String
   ): Shift @requireAuth

   "Get shift's currenty assigned service"
   AssignedService: Service @requireAuth

   "Get the latest trips done by the driver"
   HistoricalDriverServices(
      year: Int
      month: Int
      page: Int,
      count: Int
    ): [Service] @requireAuth
}

type Mutation {
   "Starts a new shift"
   startShift(
      "Vehicle's plate to use"
      vehiclePlate: String
      "Device Identifier"
      deviceIdentifier: String
   ): CommandAck @requireAuth

   "Stop currently open shift"
   stopShift: CommandAck @requireAuth

   "Sets the shift state"
   setShiftState(
      "state to set"
      state: String
   ): CommandAck @requireAuth

   "Accept a service offer"
   acceptServiceOffer(
      "Shift id"
      shiftId: String
      "Service Id"
      serviceId: String
      "Current shift location"
      location: PointInput
   ): CommandAck @requireAuth

   "Send a message to the client"
   sendMessageToClient(
      "Service ID"
      serviceId: String!
      "Message"
      message: ChatMessageInput!
   ): CommandAck @requireAuth
}