type CommandResponse {
  "Response code"
  code: Int
  "Response message"
  message: String
}

"Coordinates"
type ServiceCoordinate {
   "Latitude"
   lat: Float
   "Longitude"
   lng: Float
   "Timestamp of the coordinate"
   timestamp: BigInt
}

"Service Location info"
type ServiceServiceLocation {
  "Accurate location, Exact marker point: Lat,Lng"
  marker: ServiceCoordinate
  "Non-Accurate location, describes an area"
  polygon: [ServiceCoordinate]
  "City name"
  city: String
  "Zone name"
  zone: String
  "Neighborhood name"
  neighborhood: String
  "Street address 1"
  addressLine1: String
  "Street address 2"
  addressLine2: String
  "location notes"
  notes: String
}

"Client info."
type ServiceServiceClient {
  "Client id"
  id: String!
  "Business id where the client belongs"
  businessId: String!
  "Username of the client"
  username: String
  "Full name"
  fullname: String
  "Tip for the client"
  tip: Int
  "Tip type"
  tipType: String
}

"Driver info"
type ServiceServiceDriver {
  "Document ID"
  documentId: String!
  "Full name"
  fullname: String!  
}

"Vehicle info"
type ServiceServiceVehicle {
  "License plate of the vehicle"
  licensePlate: String!
}

"Service state"
type ServiceServiceState {
  "State"
  state: String!
  "Timestamp state"
  timestamp: BigInt!
  "Coordinate"
  location: ServiceCoordinate
  "Notes"
  notes: String
}

type ServiceClientSatellite {
  _id: String
  "General info of the client"
  generalInfo: ServiceClientSatelliteGeneralInfo
  "Location of the client"
  location: ServiceClientSatelliteLocation,
  "Client auth credential"
  auth: ServiceClientAuth
  "Client state"
  state: String
  "Business of the client"
  businessId: String
}

type ServiceClientAuth {
  "username"
  username: String!
  "User keycloak ID"
  userKeycloakId: String!
}

type ServiceClientSatelliteGeneralInfo {
  "Client name"
  name: String!
  "Client phone"
  phone: BigInt
  "Client address"
  address: String
  "Client city"
  city: String
  "Client email"
  email: String
  "Client neighborhood"
  neighborhood: String
  "Referrer driver document id"
  referrerDriverDocumentId: String
}

type ServiceClientSatelliteLocation {
  lat: Float
  lng: Float
}

type ServiceService {
  "Service ID"
  _id: ID!
  "Business ID"
  businessId: String!
  "Shift ID"
  shiftId: String
  "Timestamp service"
  timestamp: BigInt!
  "Requested features keys"
  requestedFeatures: [String]
  "Passenger pick up location"
  pickUp: ServiceServiceLocation
  "Passenger drop off location"
  dropOff: ServiceServiceLocation
  "Pick up time"
  pickUpETA: BigInt
  "Drop off time"
  dropOffETA: BigInt
  "Service verification code"
  verificationCode: String
  "Payment type key"
  paymentType: String
  "Applicable fare discount"
  fareDiscount: Float
  "pre calculated fare"
  fare: BigInt
  "current service state"
  state: String
  "State changes of the services"
  stateChanges: [ServiceServiceState]
  "Service location"
  location: ServiceCoordinate
  "Vehicle info"
  vehicle: ServiceServiceVehicle
  "Driver info"
  driver: ServiceServiceDriver
  "Client info"
  client: ServiceServiceClient
  "Service tip"
  tip: Int
  "Exact route taken by the driver"
  route: [ServiceCoordinate]
  lastModificationTimestamp: BigInt  
}

input ServiceServiceFilterInput {
  "ID of the business"
  businessId: String
  "Init date"
  initTimestamp: BigInt!
  "End date"
  endTimestamp: BigInt!
  "Driver document id"
  driverDocumentId: String
  "Driver fullname"
  driverFullname: String
  "Vehicle license plate"
  vehicleLicensePlate: String
  "Client username "
  clientUsername: String
  "Client fullname"
  clientFullname: String
  "State"
  states: [String]
  "Show closed services"
  showClosedServices: Boolean
}

input ServiceServicePaginationInput {
  "Page"
  page: Int!
  "Count"
  count: Int!
  "Sort, default: ASC"
  sort: Int
}



##  SHIFT SEGMENT  ##

input ServiceShiftPaginationInput {
  "Page"
  page: Int!
  "Count"
  count: Int!
  "Sort, default: ASC"
  sort: Int
}

type ServiceShiftDriver {
  "Driver ID"
  id: String
  "Driver fullname"
  fullname: String
  "Driver Blocks"
  blocks: [String]
  "Driver Document Type"
  documentType: String
  "Driver document id"
  documentId: String
  "Driver PMR state"
  pmr: Boolean
  "Driver Languages"
  languages: [String]
  "Driver phone"
  phone: String
  "Driver username"
  username: String
}

type ServiceShiftVehicle {
  "Vehicle id"
  id: String
  "VehicleLicense Plate"
  licensePlate: String
  "Vehicle blocks"
  blocks: [String]
  "Vehicle features"
  features: [String]
  "Vehicle brand"
  brand: String
  "Vehicle line"
  line: String
  "Vehicle model"
  model: String
}

type ServiceShiftStateChange {
  "State change name"
  state: String
  "State Change timestamp"
  timestamp: BigInt
}

type ServiceShiftOnlineChange {
  "online change status"
  online: Boolean
  "online change timestamp"
  timestamp: BigInt
}

type ServiceShiftLocation {
  "location type"
  type: String
  "Location Coordinates"
  coordinates: [Float]
}

input ServiceShiftFilterInput {
  "ID of the business"
  businessId: String
  "Init date"
  initTimestamp: BigInt
  "End date"
  endTimestamp: BigInt
  "Driver document id"
  driverDocumentId: String
  "Driver fullname"
  driverFullname: String
  "Vehicle license plate"
  vehicleLicensePlate: String
  "State"
  states: [String]
  "Include closed Shifts"
  showClosedShifts: Boolean
}

type ServiceShift {
  "Service ID"
  _id: ID!
  "Business ID"
  businessId: String!
  "Last update timestamp"
  timestamp: BigInt
  "Shift State"
  state: String
  "Shift State changes" 
  stateChanges: [ServiceShiftStateChange]
  "Shift online status"
  online: Boolean
  "Shift online changes"
  onlineChanges: [ServiceShiftOnlineChange]
  "Shift last received comunication"
  lastReceivedComm: BigInt
  "Shift current location"
  location: ServiceShiftLocation  
  "Shift driver"
  driver: ServiceShiftDriver
  "Shift vehicle"
  vehicle: ServiceShiftVehicle
}

type Query {
  ## CLIENT SATELLITE
  ServiceClientSatellite: ServiceClientSatellite
  "Gets the client satellite by its name"
  ServiceClientSatellites(clientText: String, limit: Int): [ServiceClientSatellite]
  "Get Services with state REQUESTED, ASSIGNED AND ARRIVED that belongs to the client satellite logged."
  ServiceServicesSatellite: [ServiceService]
  "Get client satellite data of the client satellite logged"
  "Get Services filtered"
  ServiceServices(filterInput: ServiceServiceFilterInput!, paginationInput: ServiceServicePaginationInput!): [ServiceService]
  "Get the amount of Services filtered "
  ServiceServicesSize(filterInput: ServiceServiceFilterInput!): Int!
  "Get Service by its id"
  ServiceService(id: String!): ServiceService
  ## SHIFTS
  "Get Shift filtered"
  ServiceShifts(filterInput: ServiceShiftFilterInput!, paginationInput: ServiceShiftPaginationInput!): [ServiceShift]
  "Get amount of Shifts filtered"
  ServiceShiftsSize(filterInput: ServiceShiftFilterInput!): Int!
  "Get shift by its id"
  ServiceShift(id: String!): ServiceShift
  "Get Shift changeStates List @param id: Shift id"
  ServiceShiftStateChangesList(id: String!, paginationInput: ServiceShiftPaginationInput! ): [ServiceShiftStateChange]
  "Get Shift changeStates List Size @param id: Shift id"
  ServiceShiftStateChangesListSize(id: String!): Int!
  "Get Shift changeStates List @param id: Shift id"
  ServiceShiftOnlineChangesList(id: String!, paginationInput: ServiceShiftPaginationInput! ): [ServiceShiftOnlineChange]
  "Get Shift changeStates List Size @param id: Shift id"
  ServiceShiftOnlineChangesListSize(id: String!): Int!
}

type Subscription {
  "This events is triggered when a Service is created or updated"
  ServiceServiceUpdatedSubscription: ServiceService  
}